"""Regenerate OULAD numeric figures from completed TLT result artifacts.

No model is fitted and raw learner data are not required. The three figures
used in the main paper are generated by default; --extra also refreshes the
five supporting numeric figures. Existing conceptual diagrams are untouched.
The default figures need aggregate tables only. Supporting hazard-prevalence
and calibration figures also need locally saved membership and prediction
artifacts from a completed experiment.

Example:
    python3 scripts/regenerate_tlt_figures.py \
        --results tlt_submission_time_v1/main/oulab \
        --output-dir paper_tlt_riskset/figures --extra
"""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.colors import TwoSlopeNorm
from matplotlib.ticker import MaxNLocator
import numpy as np
import pandas as pd

OULAD: Path
OULAD_HAZARD: Path
OUT: Path
INPUTS: set[Path] = set()


def read_csv(path, **kwargs):
    """Preserve saved floating-point probabilities, including tied scores."""
    INPUTS.add(Path(path).resolve())
    return pd.read_csv(path, float_precision="round_trip", **kwargs)


BLUE = "#0072B2"

ORANGE = "#E69F00"

GREEN = "#009E73"

RED = "#D55E00"

PURPLE = "#CC79A7"

GREY = "#666666"

ORANGE_TX = "#7A5300"

GREEN_TX = "#006B4F"

RED_TX = "#963D00"

PURPLE_TX = "#7F4267"

INK = "#222222"

MODEL_LABELS = {
    "base_lr_profile": "Profile LR",
    "base_lr_clickstream": "Cumulative LR",
    "base_lr_weekly": "Weekly LR",
    "base_rf_gini": "RF (Gini)",
    "base_rf_entropy": "RF (entropy)",
    "base_svm": "Linear SVM",
    "base_knn": "kNN",
    "base_dffnn": "DFFNN",
    "flat_hgb": "Flat HGB",
    "temporal_hgb": "Temporal HGB",
    "stack_7_full": "Rich temporal stack",
}

def style() -> None:
    plt.rcParams.update(
        {
            "font.family": "DejaVu Sans",
            "font.size": 8,
            "axes.titlesize": 8,
            "axes.labelsize": 8,
            "xtick.labelsize": 7,
            "ytick.labelsize": 7,
            "legend.fontsize": 7,
            "axes.linewidth": 0.7,
            "lines.linewidth": 1.4,
            "lines.markersize": 3.5,
            "savefig.bbox": "tight",
            "savefig.pad_inches": 0.02,
            "pdf.fonttype": 42,
        }
    )

def save(fig: plt.Figure, name: str) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    fig.savefig(OUT / f"{name}.pdf")
    fig.savefig(OUT / f"{name}.png", dpi=300)
    plt.close(fig)

def population_trajectory() -> None:
    comp = read_csv(OULAD / "cohort_composition.csv")
    d = comp[comp["table"].eq("indices")].sort_values("week")
    fig, axes = plt.subplots(1, 2, figsize=(7.16, 2.55))

    ax = axes[0]
    ax.plot(d.week, d.n_activity, "o-", color=BLUE, label="Activity-conditioned")
    ax.plot(d.week, d.n_cutoff_valid, "s-", color=GREEN, label="Cutoff-valid")
    ax.set(xlabel="Landmark week", ylabel="Learner-presentations", title="(a) Population size")
    ax.legend(frameon=False, loc="best")

    ax = axes[1]
    ax.plot(d.week, 100 * d.activity_contamination_rate, "o-", color=RED, label="Known-outcome contamination")
    ax.plot(d.week, 100 * d.silent_exclusion_rate, "s-", color=ORANGE, label="Eligible-silent exclusion")
    ax.set(xlabel="Landmark week", ylabel="Share (%)", title="(b) Validity errors")
    ax.legend(frameon=False, loc="best")
    for ax in axes:
        ax.xaxis.set_major_locator(MaxNLocator(integer=True))
        ax.grid(alpha=0.25, linewidth=0.5)
        ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout(w_pad=2.0)
    save(fig, "fig2_population_trajectory")

def _median_band(ax, frame, metric, color, label, contrast=None, linestyle="-"):
    d = frame[frame.metric.eq(metric)]
    if contrast is not None:
        d = d[d.contrast.eq(contrast)]
    g = d.groupby("week").delta.agg(
        median="median", q1=lambda s: s.quantile(0.25), q3=lambda s: s.quantile(0.75)
    )
    marker = {"joint_population_difference": "o", "evaluation_population_shapley": "s",
              "training_population_shapley": "^"}.get(contrast, "o")
    ax.plot(g.index, g["median"], marker=marker, linestyle=linestyle, color=color, label=label)
    ax.fill_between(g.index, g.q1, g.q3, color=color, alpha=0.18, linewidth=0)

def _path_span(ax, frame, metric, color, contrast_a, contrast_b):
    """Shade between the two traversals of the 2x2 design.

    This is the range between path-specific medians across configurations,
    not a confidence interval or the median cellwise interaction.
    """
    d = frame[frame.metric.eq(metric)]
    a = d[d.contrast.eq(contrast_a)].groupby("week").delta.median()
    b = d[d.contrast.eq(contrast_b)].groupby("week").delta.median()
    joined = pd.concat([a, b], axis=1, keys=["a", "b"]).dropna()
    ax.fill_between(
        joined.index,
        joined[["a", "b"]].min(axis=1),
        joined[["a", "b"]].max(axis=1),
        color=color,
        alpha=0.30,
        linewidth=0,
    )

def metric_distortion() -> None:
    od = read_csv(OULAD / "training_evaluation_decomposition.csv")
    fig, axes = plt.subplots(1, 2, figsize=(7.16, 2.55))
    contrasts = [
        ("joint_population_difference", BLUE, "Joint: A→A minus V→V", "-"),
        ("evaluation_population_shapley", RED, "Evaluation (symmetric)", "-"),
        ("training_population_shapley", GREEN, "Training (symmetric)", "--"),
    ]
    spans = [
        (
            RED,
            "evaluation_population_component",
            "evaluation_population_component_at_valid",
        ),
        (
            GREEN,
            "training_population_component",
            "training_population_component_at_activity",
        ),
    ]
    for ax, metric, title in zip(
        axes,
        ["auc", "pr_auc_risk"],
        ["(a) ROC-AUC decomposition", "(b) Adverse-outcome PR-AUC decomposition"],
    ):
        for color, contrast_a, contrast_b in spans:
            _path_span(ax, od, metric, color, contrast_a, contrast_b)
        for contrast, color, label, linestyle in contrasts:
            _median_band(ax, od, metric, color, label, contrast, linestyle)
        ax.set(title=title, xlabel="Landmark week", ylabel="Raw metric difference")
        ax.xaxis.set_major_locator(MaxNLocator(integer=True))
        ax.legend(frameon=False, loc="best", fontsize=6)

    for ax in axes:
        ax.axhline(0, color="black", linewidth=0.7)
        ax.grid(alpha=0.25, linewidth=0.5)
        ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout(w_pad=2.0)
    save(fig, "fig3_metric_distortion")

def decision_distortion() -> None:
    ob = read_csv(OULAD / "budget_performance.csv")
    ob = ob[
        ob.protocol.eq("activity_conditioned")
        & ob.reference_protocol.eq("cutoff_valid")
        & ob.budget.eq(0.05)
    ]
    oo = read_csv(OULAD / "decision_overlap.csv")
    oo = oo[oo.budget.eq(0.05)]

    fig, axes = plt.subplots(1, 2, figsize=(7.16, 2.55))
    overlap_specs = [
        ("protocol", "activity_conditioned", "cutoff_valid", BLUE, "Joint: A→A vs V→V"),
        ("evaluation_population", "activity_conditioned", "activity_to_cutoff_valid", RED, "Candidate population: A→A vs A→V"),
        ("protocol", "activity_to_cutoff_valid", "cutoff_valid", GREEN, "Refitting: A→V vs V→V"),
    ]
    marks = {BLUE: ("^", "-", 1.8), RED: ("s", (0, (3, 2)), 1.5), GREEN: ("o", "-", 2.2)}
    for comparison, protocol, reference, color, label in overlap_specs:
        d = oo[
            oo.comparison_type.eq(comparison)
            & oo.protocol.eq(protocol)
            & oo.reference_protocol.eq(reference)
        ].groupby("week_from").jaccard.median()
        marker, dash, width = marks[color]
        axes[0].plot(d.index, d.values, color=color, marker=marker, linestyle=dash,
                     linewidth=width, markersize=3.8, label=label)
    axes[0].set(title="(a) Top-5% decision overlap", xlabel="Landmark week", ylabel="Jaccard agreement", ylim=(0, 1.0))
    axes[0].legend(frameon=False)

    # A->V and V->V are exactly zero at every landmark. The thick-solid under
    # thin-dashed pairing keeps the two coincident series separable instead of
    # rendering them as a single line.
    budget = read_csv(OULAD / "budget_performance.csv")
    for protocol, label in [("cutoff_valid", "$V{\\to}V$"),
                            ("activity_to_cutoff_valid", "$A{\\to}V$"),
                            ("activity_conditioned", "$A{\\to}A$")]:
        d = (budget[budget.protocol.eq(protocol) & budget.budget.eq(0.05)]
             .groupby("week").wasted_budget_rate.median())
        axes[1].plot(d.index, d.values, label=label, **SERIES_STYLE[protocol])
    axes[1].set(title="(b) Noneligible allocation at 5%", xlabel="Landmark week",
                ylabel="Proportion", ylim=(0, 1.0))
    _zero_note(axes[1], "$A{\\to}V$ and $V{\\to}V$ coincide at $0$", y=0.06)
    axes[1].legend(frameon=False, loc="upper left")

    for ax in axes:
        ax.xaxis.set_major_locator(MaxNLocator(integer=True))
        ax.grid(alpha=0.25, linewidth=0.5)
        ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout(w_pad=2.0)
    save(fig, "fig4_decision_distortion")

def subgroup_omission() -> None:
    cat = read_csv(OULAD / "excluded_profile_categorical.csv")
    d = cat[cat.week.eq(2)]
    wanted = [
        ("gender", "F", "Women"),
        ("disability", "Y", "Declared disability"),
        ("imd_band", "0-10%", "Most deprived IMD band"),
        ("highest_education", "Lower Than A Level", "Below A-level entry"),
        ("highest_education", "No Formal quals", "No formal qualifications"),
    ]
    rows = []
    for attr, group, label in wanted:
        x = d[d.attribute.eq(attr) & d.group.eq(group)].set_index("observability")
        rows.append(
            {
                "label": label,
                "share_gap": 100 * (x.loc["eligible_silent", "share"] - x.loc["eligible_active", "share"]),
                "risk_gap": 100 * (x.loc["eligible_silent", "risk_rate"] - x.loc["eligible_active", "risk_rate"]),
            }
        )
    frame = pd.DataFrame(rows).sort_values("share_gap")
    y = np.arange(len(frame))
    fig, axes = plt.subplots(1, 2, figsize=(7.16, 2.7), sharey=True)
    axes[0].barh(y, frame.share_gap, color=GREEN)
    axes[0].axvline(0, color="black", linewidth=0.7)
    axes[0].set(title="(a) Representation among silent vs. active", xlabel="Share difference (percentage points)", yticks=y, yticklabels=frame.label)
    axes[1].barh(y, frame.risk_gap, color=ORANGE)
    axes[1].axvline(0, color="black", linewidth=0.7)
    axes[1].set(title="(b) Adverse-outcome concentration", xlabel="Prevalence difference (percentage points)")
    for ax in axes:
        ax.grid(axis="x", alpha=0.25, linewidth=0.5)
        ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout(w_pad=1.2)
    save(fig, "fig5_subgroup_omission")

def model_heterogeneity() -> None:
    distortion = read_csv(OULAD / "metric_distortion.csv")
    distortion = distortion[
        distortion.metric.eq("auc")
        & distortion.reference_protocol.eq("cutoff_valid")
        & distortion.protocol.isin(["activity_conditioned", "static_full"])
    ]
    order = list(MODEL_LABELS)
    weeks = sorted(distortion.week.unique())
    values = []
    for protocol in ["activity_conditioned", "static_full"]:
        pivot = (
            distortion[distortion.protocol.eq(protocol)]
            .pivot(index="model", columns="week", values="delta")
            .reindex(index=order, columns=weeks)
        )
        values.append(pivot)

    bound = max(abs(min(v.min().min() for v in values)), abs(max(v.max().max() for v in values)))
    norm = TwoSlopeNorm(vmin=-bound, vcenter=0, vmax=bound)
    fig, axes = plt.subplots(1, 2, figsize=(7.16, 3.55), sharey=True)
    titles = ["(a) Activity-conditioned minus valid", "(b) Static-full minus valid"]
    image = None
    for ax, pivot, title in zip(axes, values, titles):
        image = ax.imshow(pivot.values, cmap="RdBu_r", norm=norm, aspect="auto")
        ax.set(
            title=title,
            xlabel="Landmark week",
            xticks=np.arange(len(weeks)),
            xticklabels=weeks,
            yticks=np.arange(len(order)),
            yticklabels=[MODEL_LABELS[m] for m in order],
        )
        ax.tick_params(length=0)
        for x in np.arange(0.5, len(weeks), 1):
            ax.axvline(x, color="white", linewidth=0.5, alpha=0.7)
        for y in np.arange(0.5, len(order), 1):
            ax.axhline(y, color="white", linewidth=0.5, alpha=0.7)
    fig.subplots_adjust(left=0.16, right=0.88, bottom=0.13, top=0.90, wspace=0.08)
    cbar_ax = fig.add_axes([0.91, 0.14, 0.018, 0.72])
    cbar = fig.colorbar(image, cax=cbar_ax)
    cbar.set_label("ROC-AUC difference")
    save(fig, "fig6_model_heterogeneity")

SERIES_STYLE = {
    "cutoff_valid": dict(color=GREEN, marker="o", linestyle="-", linewidth=2.8,
                         markersize=4.6, zorder=2),
    "activity_to_cutoff_valid": dict(color=RED, marker="s", linestyle=(0, (3, 2)),
                                     linewidth=1.5, markersize=3.2, zorder=3),
    "activity_conditioned": dict(color=BLUE, marker="^", linestyle="-",
                                 linewidth=1.8, markersize=4.0, zorder=4),
}

def _zero_note(ax, text, y=0.045):
    """Label series that are identically zero instead of hiding them."""
    ax.annotate(text, xy=(0.5, y), xycoords=("axes fraction", "data"),
                ha="center", va="bottom", fontsize=6.0, color=INK)

def budget_response() -> None:
    budget = read_csv(OULAD / "budget_performance.csv")
    protocols = ["cutoff_valid", "activity_to_cutoff_valid", "activity_conditioned"]
    labels = {
        "cutoff_valid": "Cutoff-valid",
        "activity_to_cutoff_valid": "Activity-trained, valid-scored",
        "activity_conditioned": "Activity-conditioned",
    }
    fig, axes = plt.subplots(2, 2, figsize=(7.16, 4.45), sharex=True)
    for col, week in enumerate([2, 16]):
        frame = budget[budget.week.eq(week)]
        for protocol in protocols:
            d = (
                frame[frame.protocol.eq(protocol)]
                .groupby("budget")
                .agg(
                    actionable_precision=("actionable_precision", "median"),
                    waste=("wasted_budget_rate", "median"),
                )
            )
            x = 100 * d.index.to_numpy()
            style = SERIES_STYLE[protocol]
            axes[0, col].plot(x, d.actionable_precision, label=labels[protocol], **style)
            axes[1, col].plot(x, d.waste, **style)
        # Both valid-scored protocols sit exactly on zero; the thick-solid under
        # thin-dashed pairing keeps them separable, and the note removes any
        # doubt that two series are present rather than one.
        _zero_note(axes[1, col], "both valid-scored protocols $\\equiv 0$", y=0.025)
        axes[0, col].set_title(f"({'a' if col == 0 else 'b'}) Eligibility-adjusted precision, wk {week}")
        axes[1, col].set_title(f"({'c' if col == 0 else 'd'}) Noneligible allocation, wk {week}")
        axes[1, col].set_xlabel("Intervention budget (%)")
        for row in range(2):
            axes[row, col].set_ylim(-0.03, 1.03)
            axes[row, col].set_xticks([1, 5, 10, 20])
            axes[row, col].grid(alpha=0.25, linewidth=0.5)
            axes[row, col].spines[["top", "right"]].set_visible(False)
    axes[0, 0].set_ylabel("Precision")
    axes[1, 0].set_ylabel("Proportion")
    handles, legend_labels = axes[0, 0].get_legend_handles_labels()
    fig.legend(handles, legend_labels, ncol=3, frameon=False, loc="lower center")
    fig.tight_layout(rect=(0, 0.07, 1, 1), h_pad=1.4, w_pad=1.5)
    save(fig, "fig7_budget_response")

def _hazard_prevalence() -> pd.DataFrame:
    """Recover the seven-day label directly from the saved eligible roster."""
    frame = read_csv(OULAD / "cohort_membership.csv.gz")
    frame = frame.loc[frame.cutoff_valid].copy()
    if frame.duplicated(["week", "id_student", "code_module", "code_presentation"]).any():
        raise ValueError("Duplicate enrolment-landmark rows in cohort membership")
    frame["hazard_event"] = (
        frame.date_unregistration.ge(frame.cutoff_day)
        & frame.date_unregistration.lt(frame.cutoff_day + 7)
    ).astype(int)
    return (
        frame.groupby("week")
        .hazard_event.agg(event_rate="mean", n="size")
        .rename_axis("week")
        .reset_index()
    )

def hazard_benchmark() -> None:
    summary = read_csv(OULAD_HAZARD / "discrete_hazard_summary.csv")
    auc = summary.groupby("week").auc_mean.agg(
        median="median", q1=lambda s: s.quantile(0.25), q3=lambda s: s.quantile(0.75)
    )
    full = summary[summary.model.eq("stack_7_full")].set_index("week")
    prevalence = _hazard_prevalence().set_index("week")
    if not np.array_equal(summary.n.to_numpy(), summary.week.map(prevalence.n).to_numpy()):
        raise ValueError("Hazard summary counts differ from saved eligible roster")
    # Separate size and prevalence axes avoid suggesting a relationship through
    # independently adjustable scales on a dual-axis plot.
    fig, axes = plt.subplots(1, 3, figsize=(7.16, 2.6),
                             gridspec_kw={"width_ratios": [1.55, 1, 1]})
    ax = axes[0]
    ax.fill_between(auc.index, auc.q1, auc.q3, color=BLUE, alpha=0.18,
                    linewidth=0, label="Model IQR")
    ax.plot(auc.index, auc["median"], "o-", color=BLUE, label="Model median")
    ax.errorbar(full.index, full.auc_mean,
                yerr=[full.auc_mean-full.auc_ci_low, full.auc_ci_high-full.auc_mean],
                fmt="s-", color=RED, capsize=2, label="Rich stack (95% CI)")
    ax.set(title="(a) Withdrawal discrimination", ylabel="ROC-AUC", ylim=(0.5, 0.9))
    ax.legend(frameon=False, loc="lower right", fontsize=6)
    axes[1].plot(prevalence.index, prevalence.n/1000, "s-", color=GREEN)
    axes[1].set(title="(b) Eligible population", ylabel="Enrolments (thousands)")
    axes[2].plot(prevalence.index, 100*prevalence.event_rate, "o--", color=ORANGE)
    axes[2].set(title="(c) Seven-day events", ylabel="Withdrawal in next 7 days (%)")
    for ax in axes:
        ax.set_xlabel("Landmark week")
        ax.set_xticks([2, 8, 16])
        ax.grid(alpha=0.25, linewidth=0.5)
        ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout(w_pad=1.5)
    save(fig, "fig8_hazard_benchmark")

def _selected_predictions() -> pd.DataFrame:
    path = OULAD / "predictions.csv.gz"
    usecols = ["week", "protocol", "model", "risk", "risk_score"]
    pieces = []
    checkpoints = [OULAD / "checkpoints" / f"week_{week:03d}__stack_7_full.csv.gz"
                   for week in (2, 16)]
    if all(checkpoint.is_file() for checkpoint in checkpoints):
        chunks = (read_csv(checkpoint, usecols=usecols) for checkpoint in checkpoints)
    else:
        chunks = read_csv(path, usecols=usecols, chunksize=250_000)
    for chunk in chunks:
        selected = chunk[
            chunk.model.eq("stack_7_full")
            & chunk.week.isin([2, 16])
            & chunk.protocol.isin(["activity_conditioned", "cutoff_valid", "static_full"])
        ]
        if not selected.empty:
            pieces.append(selected)
    return pd.concat(pieces, ignore_index=True)

def calibration_profiles() -> None:
    frame = _selected_predictions()
    protocols = ["cutoff_valid", "activity_conditioned", "static_full"]
    labels = {
        "cutoff_valid": "Cutoff-valid",
        "activity_conditioned": "Activity-conditioned",
        "static_full": "Static-full",
    }
    colors = {
        "cutoff_valid": GREEN,
        "activity_conditioned": BLUE,
        "static_full": PURPLE,
    }
    fig, axes = plt.subplots(1, 2, figsize=(7.16, 2.85))
    for ax, week, panel in zip(axes, [2, 16], ["a", "b"]):
        for protocol in protocols:
            d = frame[frame.week.eq(week) & frame.protocol.eq(protocol)].copy()
            d["bin"] = pd.qcut(d.risk_score, q=10, duplicates="drop")
            curve = d.groupby("bin", observed=True).agg(
                predicted=("risk_score", "mean"), observed=("risk", "mean"), n=("risk", "size")
            )
            marker = {"cutoff_valid": "o", "activity_conditioned": "s", "static_full": "^"}[protocol]
            dash = {"cutoff_valid": "-", "activity_conditioned": "--", "static_full": ":"}[protocol]
            ax.plot(curve.predicted, curve.observed, marker=marker, linestyle=dash,
                    color=colors[protocol], label=labels[protocol])
        ax.plot([0, 1], [0, 1], "--", color="black", linewidth=0.8)
        ax.set(
            title=f"({panel}) Full-stack calibration, week {week}",
            xlabel="Mean predicted adverse-outcome risk",
            ylabel="Observed adverse-outcome rate",
            xlim=(0, 1),
            ylim=(0, 1),
        )
        ax.grid(alpha=0.25, linewidth=0.5)
        ax.spines[["top", "right"]].set_visible(False)
    axes[0].legend(frameon=False, loc="upper left")
    fig.tight_layout(w_pad=2.0)
    save(fig, "fig9_calibration_profiles")


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results", type=Path, required=True,
                        help="OULAD results with protocol.json or fit_protocol_original.json")
    parser.add_argument("--output-dir", type=Path, default=Path("paper_tlt_riskset/figures"))
    parser.add_argument("--extra", action="store_true", help="Also regenerate supporting figures 5-9")
    return parser.parse_args()


def main():
    global OULAD, OULAD_HAZARD, OUT
    args = parse_args()
    OULAD = args.results.expanduser().resolve()
    OULAD_HAZARD = OULAD
    OUT = args.output_dir.expanduser().resolve()
    protocol_path = OULAD / "protocol.json"
    if not protocol_path.is_file():
        protocol_path = OULAD / "fit_protocol_original.json"
    protocol = json.loads(protocol_path.read_text(encoding="utf-8"))
    if protocol.get("dataset") != "oulab":
        raise ValueError("This figure suite requires an OULAD result directory")
    if args.extra and protocol.get("hazard_days") != 7:
        raise ValueError("Supporting hazard figures require a seven-day interval")
    INPUTS.add(protocol_path)
    required = ["cohort_composition.csv", "training_evaluation_decomposition.csv",
                "budget_performance.csv", "decision_overlap.csv"]
    if args.extra:
        required += ["excluded_profile_categorical.csv", "metric_distortion.csv",
                     "discrete_hazard_summary.csv", "cohort_membership.csv.gz"]
    missing = [name for name in required if not (OULAD / name).is_file()]
    if missing:
        raise FileNotFoundError("Missing figure inputs: " + ", ".join(missing))
    style()
    for plot in [population_trajectory, metric_distortion, decision_distortion]:
        plot()
        print(f"[figure] {plot.__name__}", flush=True)
    if args.extra:
        for plot in [subgroup_omission, model_heterogeneity, budget_response,
                     hazard_benchmark, calibration_profiles]:
            plot()
            print(f"[figure] {plot.__name__}", flush=True)
    hashes = {}
    for path in sorted(INPUTS):
        digest = hashlib.sha256()
        with path.open("rb") as stream:
            for block in iter(lambda: stream.read(1024 * 1024), b""):
                digest.update(block)
        hashes[path.relative_to(OULAD).as_posix()] = digest.hexdigest()
    (OUT / "figure_inputs.json").write_text(json.dumps({
        "dataset": "oulab", "weeks": protocol.get("weeks"),
        "models": protocol.get("models"), "fit_metadata_file": protocol_path.name,
        "input_sha256": hashes,
        "decomposition_bands": "model interquartile ranges and ranges between path-specific medians; not confidence intervals",
        "hazard_error_bars": "paired presentation-cluster 95% bootstrap intervals in the saved hazard summary",
    }, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
